<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9DC45GS" failures="2" tests="2" name="Runner.testRunner" time="19.965" errors="0" timestamp="2024-11-17T21:54:33 IST" skipped="0">
  <testcase classname="Runner.testRunner" name="runScenario" time="9.671">
    <failure message="expected [yash] but found [System Users]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [yash] but found [System Users]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at pages.loginPage.clickadminbutton(loginPage.java:53)
at stepDefinition.secondTest.user_clicks_on_admin_page(secondTest.java:46)
at ✽.user clicks on admin page(file:///C:/Users/Rushitha/Documents/yash/my-app/src/test/resources/Feature/login.feature:40)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.testRunner" name="runScenario" time="10.294">
    <failure message="expected [yash] but found [System Users]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [yash] but found [System Users]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at pages.loginPage.clickadminbutton(loginPage.java:53)
at stepDefinition.firstTest.user_clicks_on_admin_button(firstTest.java:47)
at ✽.user clicks on admin button(file:///C:/Users/Rushitha/Documents/yash/my-app/src/test/resources/Feature/login.feature:31)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Runner.testRunner -->
